FROM php:8.1-fpm-alpine
LABEL maintainer="Eduardo Andrade <eduardoandrade@simbi.social>"

ENV COMPOSER_ALLOW_SUPERUSER=1

RUN apk update
RUN apk add wget

# Add composer
COPY --from=composer /usr/bin/composer /usr/bin/composer

# Add PHP extensions
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions ds pdo_pgsql pgsql intl sockets xdebug-stable

WORKDIR /var/www/html
USER 1000:1000
EXPOSE 8000
